routes/web.php
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function(){
            Route::get('/', 'ProfileController@index')->name('index');
            Route::group(['middleware' => 'auth.primary'], function(){
                Route::get('/edit', 'ProfileController@edit')->name('edit');
                Route::put('/update', 'ProfileController@update')->name('update');
            });
            
        });
        
        // membership
        Route::group(['prefix' => 'membership', 'as' => 'membership.', 'middleware' => 'auth.primary'], function() {
            Route::get('/', 'MembershipController@index')->name('index');
            Route::get('/terms/{planTypeId}', 'MembershipController@terms')->name('terms');
            Route::get('/signup/{planTypeId}', 'MembershipController@signUp')->name('signup');

            Route::get('/create', 'MembershipController@create')->name('create');
            Route::post('/store', 'MembershipController@store')->name('store');
            Route::get('/edit/{pendingId}', 'MembershipController@edit')->name('edit');
            Route::put('/update', 'MembershipController@update')->name('update');
            Route::delete('/destroy/{pendingId}', 'MembershipController@delete')->name('destroy');

            Route::get('/plans', 'MembershipController@planSummary')->name('plans');
        });

        // payments
        Route::group(['prefix' => 'payments', 'as' => 'payments.', 'middleware' => 'auth.primary'], function(){
            Route::get('/', 'PaymentController@index')->name('index');
            Route::get('/paypal', 'PaymentController@paypal')->name('paypal');
            Route::get('/paypalSuccess', 'PaymentController@paypalSuccess')->name('paypalSuccess');
            Route::get('/cache', 'PaymentController@cache')->name('cache');
            Route::post('/stripe', 'PaymentController@stripe')->name('stripe');
            Route::get('/history', 'PaymentController@history')->name('history');
        });

        // members
        Route::group(['prefix' => 'members', 'as' => 'members.'], function(){
            Route::get('/', 'MemberController@index')->name('index');
            Route::group(['middleware' => 'auth.primary'], function(){
                Route::get('/planlist/{id}/{update_type}', 'MemberController@showUpgrade')->name('showupgrade');
                Route::post('/upgrade', 'MemberController@upgrade')->name('upgrade');
                Route::get('/upgrade/showterms', 'MemberController@showTerms')->name('upgrade.showterms');
                Route::get('/upgrade/showpayment', 'MemberController@showPayment')->name('upgrade.showpayment');
                Route::post('/upgrade/payment/stripe', 'MemberController@stripe')->name('upgrade.stripe');
                Route::post('/upgrade/payment/paypal', 'MemberController@paypal')->name('upgrade.paypal');
                Route::get('/upgrade/payment/paypalSuccess', 'MemberController@paypalSuccess')->name('upgrade.paypalsuccess');
                Route::post('/upgrade/payment/cache', 'MemberController@cache')->name('upgrade.cache');
            });
        });

        // pendings
        Route::group(['prefix' => 'pendings', 'as' => 'pendings.', 'middleware' => 'auth.primary'], function() {
            Route::get('/', 'MembershipController@pendings')->name('index');

            Route::get('/edit/{id}', 'MembershipController@pendings_edit')->name('edit');
            Route::put('/update', 'MembershipController@pendings_update')->name('update');
            Route::delete('/destroy/{id}', 'MembershipController@pendings_delete')->name('destroy');
        });
    });

    Route::get('/test', 'MemberController@test')->name('test');
    
});


// -------- Admin Routes ----------
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Authentication
    Route::group(['as' => 'auth.'], function() {
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('showLogin');
        Route::post('/login', 'Auth\LoginController@login')->name('login');
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
    
    Route::group(['middleware' => 'auth:admins'], function () {
        Route::get('/', 'AdminController@home')->name('home');

        // Admin Users management
        Route::resource('adminusers','AdminUserController')->except('show')->names([
            'index' => 'adminusers.index',
            'create' => 'adminusers.create',
            'store' => 'adminusers.store',
            'edit' => 'adminusers.edit',
            'update' => 'adminusers.update',
            'destroy' => 'adminusers.destroy'
        ]);

        // Users management
        Route::resource('users','UserController')->except('show')->names([
            'index' => 'users',
            'create' => 'users.create',
            'edit' => 'users.edit',
            'store' => 'users.store',
            'update' => 'users.update',
            'destroy' => 'users.destroy'
        ]);

        // Pending members management
        Route::group(['prefix' => 'users/pendingmembers', 'as' => 'pendingmembers'], function(){
            Route::get('/', 'PendingMemberController@index')->name('');
            Route::get('/create', 'PendingMemberController@create')->name('.create');
            Route::post('/store', 'PendingMemberController@store')->name('.store');
            Route::get('/edit/{id}', 'PendingMemberController@edit')->name('.edit');
            Route::put('/update/{id}', 'PendingMemberController@update')->name('.update');
            Route::put('/update/{id}', 'PendingMemberController@update')->name('.update');
            Route::delete('/{id}', 'PendingMemberController@destroy')->name('.destroy');
        });

        // print card management
        Route::group(['prefix' => 'users/print', 'as' => 'users.print.'], function(){
            Route::post('/upload', 'PrintController@uploadPhoto')->name('uploadphoto');
            Route::get('/showprint/{id}',  'PrintController@showPrint')->name('showprint');
            Route::get('/{id}', 'PrintController@edit')->name('edit');
        });

        // Payment management
        Route::group(['prefix' => 'payment', 'as' => 'payment.'], function(){
            Route::get('/pendinglist/{id}', 'PaymentController@pendingList')->name('pendinglist');
            Route::post('/pendingcheckout', 'PaymentController@pendingCheckout')->name('pendingcheckout');
            Route::get('/upgradeinfo', 'PaymentController@upgradeInfo')->name('upgradeinfo');
            Route::get('/checkout', 'PaymentController@checkout')->name('checkout');
            Route::get('/cache', 'PaymentController@cache')->name('cache');
            Route::post('/stripe', 'PaymentController@stripe')->name('stripe');
            Route::get('/paypal', 'PaymentController@paypal')->name('paypal');
            Route::get('/paypalSuccess', 'PaymentController@paypalSuccess')->name('paypalSuccess');
        });

        // Membership track
        Route::group(['prefix' => 'membertrack', 'as' => 'membertrack.'], function(){
            Route::get('/admin', 'MemberTrackController@byAdmin')->name('admin');
            Route::get('/user', 'MemberTrackController@byUser')->name('user');
        });
        

        // Slides management
        Route::resource('slides','SlideController')->except('show')->names([
            'index' => 'slides',
            'create' => 'slides.create',
            'store' => 'slides.store',
            'edit' => 'slides.edit',
            'update' => 'slides.update',
            'destroy' => 'slides.destroy'
        ]);

        // Membership Plans management
        Route::resource('memberplantypes','MemberPlanTypeController')->except('show')->names([
            'index' => 'memberplantypes',
            'edit' => 'memberplantypes.edit',
            'update' => 'memberplantypes.update'
        ]);

        // Discounts management
        Route::resource('discounts','DiscountController')->except('show')->names([
            'index' => 'discounts.index',
            'create' => 'discounts.create',
            'store' => 'discounts.store',
            'edit' => 'discounts.edit',
            'update' => 'discounts.update',
            'destroy' => 'discounts.destroy'
        ]);

        // contents
        Route::group(['prefix' => 'contents', 'as' => 'contents.'], function() {
            Route::get('/contact', 'ContentController@contactContent')->name('contact.edit');
            Route::post('/contact', 'ContentController@updateContact')->name('contact.update');

            Route::get('/body/1', 'ContentController@bodyContent')->name('mission.edit');
            Route::get('/body/2', 'ContentController@bodyContent')->name('vision.edit');
            Route::get('/body/3', 'ContentController@bodyContent')->name('value.edit');

            Route::post('/body', 'ContentController@updateBodyContent')->name('body.update');

            Route::get('/wkhours', 'ContentController@workingHours')->name('wkhours.edit');
            Route::post('/wkhours', 'ContentController@updateWorkingHours')->name('wkhours.update');

            // Testmonials management
            Route::resource('testmonial','TestmonialController')->except('show')->names([
                'index' => 'testmonial.index',
                'create' => 'testmonial.create',
                'store' => 'testmonial.store',
                'edit' => 'testmonial.edit',
                'update' => 'testmonial.update',
                'destroy' => 'testmonial.destroy'
            ]);
        });

        // membership
        Route::group(['prefix' => 'pendings', 'as' => 'pendings.'], function() {
            Route::get('/', 'PaymentOfflineController@index')->name('index');

            Route::get('/approve/{id}', 'PaymentOfflineController@approve')->name('approve');
            Route::delete('/decline/{id}', 'PaymentOfflineController@delete')->name('delete');
        });

app/Models/Testmonial.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Testmonial extends Model
{
    protected $table = "testmonials";

    protected $fillable = [
        'owner', 'content', 'description', 'image'
    ];

    protected $hidden = [];
}

app/Http/Controllers/Admin/ContentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Enums\ContentType;
use App\Models\HomeContent;
use App\Models\ContactInfo;
use App\Models\WorkingHour;
use Illuminate\Support\Facades\DB;

class ContentController extends Controller
{
    public function bodyContent(Request $request)
    {
        $segments = $request->segments();
        $id = end($segments);

        $content = HomeContent::find($id);

        return view('admin.contents.body_edit', compact(
            'content'
        ));
    }

    public function updateBodyContent(Request $request) {

        $content = HomeContent::find($request->input('id'));
        $content->content = $request->input("content");

        $imageFile = $request->img_file;
        if ($imageFile) {
            $oldFileName = public_path('files/contents/' . $content->image);
            if (file_exists($oldFileName)) {
                \File::delete($oldFileName);
            }

            $fileName = time() . '.' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path('files/contents'), $fileName);
            $content->image = $fileName;
        }

        $content->save();
        return redirect()->back();
    }

    public function contactContent() {
        $content = ContactInfo::first();

        return view('admin.contents.contact_edit', compact(
            'content'
        ));
    }

    public function updateContact(Request $request) {
        $this->validate($request, [
            'email' => 'required|email',
            'phone' => 'required',
            'address' => 'required',
            'facebook' => 'required',
            'twitter' => 'required',
            'instagram' => 'required',
            'pinterest' => 'required',
        ]);

        ContactInfo::first()->update($request->all());

        return redirect()->back();
    }

    public function workingHours() {
        $workingHours = DB::table('working_hours')->get();

        return view('admin.contents.working_edit', compact(
            'workingHours'
        ));
    }

    public function updateWorkingHours(Request $request) {
        $hourList = [];

        // dd($request->input('open_status'));
        for ($i=0; $i<7; $i++) {
            
            $status = 0;
            if (array_search(($i), $request->input('open_status')) !== false) {
                $status = 1;
            }
            
            WorkingHour::find($i+1)->update([
                'start' => $request->input('start')[$i],
                'end' => $request->input('end')[$i],
                'open_status' => $status,
            ]);
        }

        return redirect()->back();
    }
}

app/Http/Controllers/Admin/TestmonialController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Testmonial;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\TestmonialRequest;

class TestmonialController extends Controller
{
    public function index()
    {
        $testmonials = Testmonial::get();
        return view("admin.contents.testmonials.list", compact(
            'testmonials'
        ));
    }

    public function create()
    {
        return view("admin.contents.testmonials.add");
    }

    public function store(TestmonialRequest $request)
    {
        $fileName = '';

        $imageFile = $request->image;
        if ($imageFile) {
            $fileName = time() . '.' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path('files/testmonials'), $fileName);
        }

        Testmonial::Create([
            'owner' => $request->input('owner'),
            'content' => $request->input('content'),
            'description' => $request->input('description'),
            'image' => $fileName,
        ]);

        return redirect()->route("admin.contents.testmonial.index");
    }

    public function edit($id)
    {
        $testmonial = Testmonial::find($id);

        return view("admin.contents.testmonials.edit", compact(
            'testmonial'
        ));
    }

    public function update($id, TestmonialRequest $request)
    {
        $testmonial = Testmonial::find($id);
        $testmonial->owner = $request->input("owner");
        $testmonial->content = $request->input("content");
        $testmonial->description = $request->input("description");

        $imageFile = $request->image;
        if ($imageFile) {
            $oldFileName = public_path('files/testmonials/' . $testmonial->image);
            if (file_exists($oldFileName)) {
                \File::delete($oldFileName);
            }

            $fileName = time() . '.' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path('files/testmonials'), $fileName);
            $testmonial->image = $fileName;
        }

        $testmonial->save();
        return redirect()->route("admin.contents.testmonial.index");
    }

    public function destroy($id)
    {
        $testmonial = Testmonial::find($id);

        $oldFileName = public_path('files/testmonials/' . $testmonial->image);
        if (file_exists($oldFileName)) {
            \File::delete($oldFileName);
        }
        
        $testmonial->delete();

        return redirect()->route("admin.contents.testmonial.index");
    }
}

resources/views/admin/contents/testmonials/add.blade.php
@extends("admin.layouts.layout") 
@section("title","Testmonials") 
@section("subtitle","Add") 
@section("css")
@endsection
 
@section("breadcumps")
  <li><a href="{{route('admin.home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="{{route('admin.contents.testmonial.index')}}">Testmonials</a></li>
  <li class="active">Add</li>
@endsection
 
@section("content")
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!-- Default box -->
    <a href="{{route('admin.contents.testmonial.index')}}">
      <i class="fa fa-angle-double-left"></i> Back to all  <span class="text-lowercase">Testmonials</span>
    </a><br /><br />

    <form method="POST" action="{{route('admin.contents.testmonial.store')}}" enctype="multipart/form-data" accept-charset="UTF-8">
      @csrf
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Add a new testmonial</h3>
        </div>
        <!-- input field row -->
        <div class="box-body form-horizontal">

          <!-- owner -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Owner *</label>
            <div class="col-sm-10">
              <input type="text" name="owner" value="{{old('owner')}}" placeholder="Owner" class="form-control {{ $errors->has('owner') ? 'is-invalid' : '' }}" />
              @if ($errors->has("owner"))
                <span class="invalid-feedback">{{ $errors->first("owner") }}</span> 
              @endif
            </div>
          </div>
          <!--./ owner -->

          <!-- content -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Content</label>
            <div class="col-sm-10">
              <textarea rows="5" name="content" placeholder="Content" 
                class="form-control {{ $errors->has('content') ? 'is-invalid' : '' }}">{{old('content')}}</textarea>
              @if ($errors->has("content"))
                <span class="invalid-feedback">{{ $errors->first("content") }}</span>
              @endif
            </div>
          </div>
          <!--./ content -->

          <!-- description -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Description *</label>
            <div class="col-sm-10">
              <input type="text" name="description" value="{{old('description')}}" placeholder="Description" class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" />
              @if ($errors->has("description"))
                <span class="invalid-feedback">{{ $errors->first("description") }}</span> 
              @endif
            </div>
          </div>
          <!--./ description -->

          <!-- Image -->
          <div class="form-group" style="margin-top: 10px;">
            <label class="col-sm-2 control-label">Image *</label>
            <div class="col-sm-4">
              <input type="file" id="image" name="image" value="{{old('image')}}" accept="image/*"
                class="form-control {{ $errors->has('image') ? 'is-invalid' : '' }}"/>
              @if ($errors->has("image"))
                <span class="invalid-feedback">{{ $errors->first("image") }}</span>
              @endif
            </div>
            <div class="col-sm-6">
              <img id="thumb-icon" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" accept=".png" alt="thumbnail"/>
            </div>
          </div>
          <!--./ Image -->
        </div>
        <!--./ input field row -->
        <div class="box-footer">
          <div id="saveActions" class="form-group">
            <input type="hidden" name="save_action" value="save_and_back" />
            <div class="btn-group">
              <button type="submit" class="btn btn-success">
                <span class="fa fa-save" role="presentation" aria-hidden="true"></span> &nbsp;
                <span data-value="save_and_back">Save and back</span>
              </button>
            </div>
            <a href="{{route('admin.contents.testmonial.index')}}" class="btn btn-default"><span class="fa fa-ban"></span> &nbsp;Cancel</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection
 
@section("js")
<script>
  var fileTypes = ['jpg', 'jpeg', 'png'];

function readURL(input) {
    if (input.files && input.files[0]) {
      var extension = input.files[0].name.split('.').pop().toLowerCase(),  //file extension from input file
          imgType = fileTypes.indexOf(extension) > -1;
      
      if (imgType) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#thumb-icon').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
      } else {
        alert('You can select only image file.');
        var imgInput = $('#image');
        imgInput.replaceWith(imgInput.val('').clone(true));
      }
    }
}

$("#image").change(function(){
  readURL(this);
});
</script>
@endsection

resources/views/admin/contents/testmonials/edit.blade.php
@extends("admin.layouts.layout")
@php
  $owner = old("title", $testmonial->owner);
  $content = old("title", $testmonial->content);
  $image = old("title", $testmonial->image);
  $description = old("title", $testmonial->description);
@endphp
@section("title","Testmonials") 
@section("subtitle","Edit") 
 
@section("breadcumps")
  <li><a href="{{route('admin.home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="{{route('admin.contents.testmonial.index')}}">Testmonials</a></li>
  <li class="active">Edit</li>
@endsection

@section("content")
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!-- Default box -->
    <a href="{{route('admin.contents.testmonial.index')}}">
      <i class="fa fa-angle-double-left"></i> Back to all<span class="text-lowercase"></span>
    </a><br /><br />
    <form method="POST" action="{{route('admin.contents.testmonial.update', ['id' => $testmonial->id])}}" enctype="multipart/form-data" accept-charset="UTF-8">
      <input name="_method" type="hidden" value="PUT" />
      <input name="id" type="hidden" value="{{$testmonial->id}}" />
      @csrf
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit testmonial</h3>
        </div>
        <!-- input field row -->
        <div class="box-body form-horizontal">

          <!-- owner -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Owner *</label>
            <div class="col-sm-10">
              <input type="text" name="owner" value="{{$owner}}" placeholder="Owner" class="form-control {{ $errors->has('owner') ? 'is-invalid' : '' }}" />
              @if ($errors->has("owner"))
                <span class="invalid-feedback">{{ $errors->first("owner") }}</span> 
              @endif
            </div>
          </div>
          <!--./ owner -->

          <!-- content -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Content</label>
            <div class="col-sm-10">
              <textarea rows="5" name="content" placeholder="Content" 
                class="form-control {{ $errors->has('content') ? 'is-invalid' : '' }}">{{ $content }}</textarea>
              @if ($errors->has("content"))
                <span class="invalid-feedback">{{ $errors->first("content") }}</span>
              @endif
            </div>
          </div>
          <!--./ content -->

          <!-- description -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Description *</label>
            <div class="col-sm-10">
              <input type="text" name="description" value="{{ $description }}" placeholder="Description" class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" />
              @if ($errors->has("description"))
                <span class="invalid-feedback">{{ $errors->first("description") }}</span> 
              @endif
            </div>
          </div>
          <!--./ description -->

          <!-- Image -->
          <div class="form-group" style="margin-top: 10px;">
            <label class="col-sm-2 control-label">Image *</label>
            <div class="col-sm-4">
              <input type="file" id="image" name="image" value="{{ $image }}" accept="image/*"
                class="form-control {{ $errors->has('image') ? 'is-invalid' : '' }}"/>
              @if ($errors->has("image"))
                <span class="invalid-feedback">{{ $errors->first("image") }}</span>
              @endif
            </div>
            <div class="col-sm-6">
              <img id="thumb-icon" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" accept=".png" alt="thumbnail"/>
            </div>
          </div>
          <!--./ Image -->
        </div>
        <!--./ input field row -->
        <div class="box-footer">
          <div id="saveActions" class="form-group">
            <input type="hidden" name="save_action" value="save_and_back" />
            <div class="btn-group">
              <button type="submit" class="btn btn-success">
                <span class="fa fa-save" role="presentation" aria-hidden="true"></span> &nbsp;
                <span data-value="save_and_back">Save and back</span>
              </button>
            </div>
            <a href="{{route('admin.contents.testmonial.index')}}" class="btn btn-default"><span class="fa fa-ban"></span> &nbsp;Cancel</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection
 
@section("js")
<script>
  var fileTypes = ['jpg', 'jpeg', 'png'];

  function readURL(input) {
      if (input.files && input.files[0]) {
        var extension = input.files[0].name.split('.').pop().toLowerCase(),  //file extension from input file
            imgType = fileTypes.indexOf(extension) > -1;
        
        if (imgType) {
          var reader = new FileReader();

          reader.onload = function (e) {
              $('#thumb-icon').attr('src', e.target.result);
          }

          reader.readAsDataURL(input.files[0]);
        } else {
          alert('You can select only image file.');
          var imgInput = $('#img_file');
          imgInput.replaceWith(imgInput.val('').clone(true));
        }
      }
  }

  $("#img_file").change(function(){
    readURL(this);
  });
</script>
@endsection

resources/views/admin/contents/testmonials/list.blade.php
@extends("admin.layouts.layout")
@section("title","Testmonials")
@section("subtitle","List")
@section("css")
  <link rel="stylesheet" href="{{ asset('public/adminTemplate/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection
 
@section("breadcumps")
  <li><a href="{{route('admin.home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Testmonials</li>
@endsection
 
@section("content")
<div class="box box-primary">
  <div class="box-header with-border">
    <a href="{{route('admin.contents.testmonial.create')}}" class="btn btn-primary ladda-button" data-style="zoom-in">
      <span class="ladda-label">
        <i class="fa fa-plus"></i> Add testmonial
      </span>
    </a>
  </div>
  <div class="box-body">
    <table id="dataTable" class="table table-bordered table-striped display dt-responsive nowrap dataTable dtr-inline">
      <thead>
        <tr>
          <th>Owner</th>
          <th>Thumbnail</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        @foreach($testmonials as $testmonial)
        <tr>
          <td>{{$testmonial->owner}}</td>
          <td><img id="thumb-icon" src="{{ asset('public/files/testmonials') . '/' . $testmonial->image}}" alt="icon photo"/></td>
          <td>{{$testmonial->description}}</td>
          <td>
            <form action="{{route('admin.contents.testmonial.destroy', ['id' => $testmonial->id])}}" method="post" class="deleteForm">
              @csrf
              <input name="_method" type="hidden" value="DELETE">
              <a href="{{route('admin.contents.testmonial.edit',["id " => $testmonial->id])}}" class="btn btn-xs btn-primary">
                <i class="fa fa-edit"></i> Edit
              </a>
              <button type="button" class="btn btn-xs btn-danger" data-button-type="delete" onclick="onDel(event)">
                <i class="fa fa-trash"></i>Delete
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@endsection
 
@section("js")
<script src="{{ asset('public/adminTemplate/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('public/adminTemplate/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script>
  $("#dataTable").DataTable();

  function onDel(event) {
    event.preventDefault();
    $obj = $(event.target);
    if (confirm('Are you sure delete this membership?')) {
      $obj.closest('form').submit();
    }
  }
</script>
@endsection