routes/web.php
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function(){
            Route::get('/', 'ProfileController@index')->name('index');
            Route::group(['middleware' => 'auth.primary'], function(){
                Route::get('/edit', 'ProfileController@edit')->name('edit');
                Route::put('/update', 'ProfileController@update')->name('update');
            });
            
        });
        
        // membership
        Route::group(['prefix' => 'membership', 'as' => 'membership.', 'middleware' => 'auth.primary'], function() {
            Route::get('/', 'MembershipController@index')->name('index');
            Route::get('/terms/{planTypeId}', 'MembershipController@terms')->name('terms');
            Route::get('/signup/{planTypeId}', 'MembershipController@signUp')->name('signup');

            Route::get('/create', 'MembershipController@create')->name('create');
            Route::post('/store', 'MembershipController@store')->name('store');
            Route::get('/edit/{pendingId}', 'MembershipController@edit')->name('edit');
            Route::put('/update', 'MembershipController@update')->name('update');
            Route::delete('/destroy/{pendingId}', 'MembershipController@delete')->name('destroy');

            Route::get('/plans', 'MembershipController@planSummary')->name('plans');
        });

        // payments
        Route::group(['prefix' => 'payments', 'as' => 'payments.', 'middleware' => 'auth.primary'], function(){
            Route::get('/', 'PaymentController@index')->name('index');
            Route::get('/paypal', 'PaymentController@paypal')->name('paypal');
            Route::get('/paypalSuccess', 'PaymentController@paypalSuccess')->name('paypalSuccess');
            Route::get('/cache', 'PaymentController@cache')->name('cache');
            Route::post('/stripe', 'PaymentController@stripe')->name('stripe');
            Route::get('/history', 'PaymentController@history')->name('history');
        });

        // members
        Route::group(['prefix' => 'members', 'as' => 'members.'], function(){
            Route::get('/', 'MemberController@index')->name('index');
            Route::group(['middleware' => 'auth.primary'], function(){
                Route::get('/planlist/{id}/{update_type}', 'MemberController@showUpgrade')->name('showupgrade');
                Route::post('/upgrade', 'MemberController@upgrade')->name('upgrade');
                Route::get('/upgrade/showterms', 'MemberController@showTerms')->name('upgrade.showterms');
                Route::get('/upgrade/showpayment', 'MemberController@showPayment')->name('upgrade.showpayment');
                Route::post('/upgrade/payment/stripe', 'MemberController@stripe')->name('upgrade.stripe');
                Route::post('/upgrade/payment/paypal', 'MemberController@paypal')->name('upgrade.paypal');
                Route::get('/upgrade/payment/paypalSuccess', 'MemberController@paypalSuccess')->name('upgrade.paypalsuccess');
                Route::post('/upgrade/payment/cache', 'MemberController@cache')->name('upgrade.cache');
            });
        });

        // pendings
        Route::group(['prefix' => 'pendings', 'as' => 'pendings.', 'middleware' => 'auth.primary'], function() {
            Route::get('/', 'MembershipController@pendings')->name('index');

            Route::get('/edit/{id}', 'MembershipController@pendings_edit')->name('edit');
            Route::put('/update', 'MembershipController@pendings_update')->name('update');
            Route::delete('/destroy/{id}', 'MembershipController@pendings_delete')->name('destroy');
        });
    });

    Route::get('/test', 'MemberController@test')->name('test');
    
});


// -------- Admin Routes ----------
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Authentication
    Route::group(['as' => 'auth.'], function() {
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('showLogin');
        Route::post('/login', 'Auth\LoginController@login')->name('login');
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
    
    Route::group(['middleware' => 'auth:admins'], function () {
        Route::get('/', 'AdminController@home')->name('home');

        // Admin Users management
        Route::resource('adminusers','AdminUserController')->except('show')->names([
            'index' => 'adminusers.index',
            'create' => 'adminusers.create',
            'store' => 'adminusers.store',
            'edit' => 'adminusers.edit',
            'update' => 'adminusers.update',
            'destroy' => 'adminusers.destroy'
        ]);

        // Users management
        Route::resource('users','UserController')->except('show')->names([
            'index' => 'users',
            'create' => 'users.create',
            'edit' => 'users.edit',
            'store' => 'users.store',
            'update' => 'users.update',
            'destroy' => 'users.destroy'
        ]);

        // Pending members management
        Route::group(['prefix' => 'users/pendingmembers', 'as' => 'pendingmembers'], function(){
            Route::get('/', 'PendingMemberController@index')->name('');
            Route::get('/create', 'PendingMemberController@create')->name('.create');
            Route::post('/store', 'PendingMemberController@store')->name('.store');
            Route::get('/edit/{id}', 'PendingMemberController@edit')->name('.edit');
            Route::put('/update/{id}', 'PendingMemberController@update')->name('.update');
            Route::put('/update/{id}', 'PendingMemberController@update')->name('.update');
            Route::delete('/{id}', 'PendingMemberController@destroy')->name('.destroy');
        });

        // print card management
        Route::group(['prefix' => 'users/print', 'as' => 'users.print.'], function(){
            Route::post('/upload', 'PrintController@uploadPhoto')->name('uploadphoto');
            Route::get('/showprint/{id}',  'PrintController@showPrint')->name('showprint');
            Route::get('/{id}', 'PrintController@edit')->name('edit');
        });

        // Payment management
        Route::group(['prefix' => 'payment', 'as' => 'payment.'], function(){
            Route::get('/pendinglist/{id}', 'PaymentController@pendingList')->name('pendinglist');
            Route::post('/pendingcheckout', 'PaymentController@pendingCheckout')->name('pendingcheckout');
            Route::get('/upgradeinfo', 'PaymentController@upgradeInfo')->name('upgradeinfo');
            Route::get('/checkout', 'PaymentController@checkout')->name('checkout');
            Route::get('/cache', 'PaymentController@cache')->name('cache');
            Route::post('/stripe', 'PaymentController@stripe')->name('stripe');
            Route::get('/paypal', 'PaymentController@paypal')->name('paypal');
            Route::get('/paypalSuccess', 'PaymentController@paypalSuccess')->name('paypalSuccess');
        });

        // Membership track
        Route::group(['prefix' => 'membertrack', 'as' => 'membertrack.'], function(){
            Route::get('/admin', 'MemberTrackController@byAdmin')->name('admin');
            Route::get('/user', 'MemberTrackController@byUser')->name('user');
        });
        

        // Slides management
        Route::resource('slides','SlideController')->except('show')->names([
            'index' => 'slides',
            'create' => 'slides.create',
            'store' => 'slides.store',
            'edit' => 'slides.edit',
            'update' => 'slides.update',
            'destroy' => 'slides.destroy'
        ]);

        // Membership Plans management
        Route::resource('memberplantypes','MemberPlanTypeController')->except('show')->names([
            'index' => 'memberplantypes',
            'edit' => 'memberplantypes.edit',
            'update' => 'memberplantypes.update'
        ]);

        // Discounts management
        Route::resource('discounts','DiscountController')->except('show')->names([
            'index' => 'discounts.index',
            'create' => 'discounts.create',
            'store' => 'discounts.store',
            'edit' => 'discounts.edit',
            'update' => 'discounts.update',
            'destroy' => 'discounts.destroy'
        ]);

        // contents
        Route::group(['prefix' => 'contents', 'as' => 'contents.'], function() {
            Route::get('/contact', 'ContentController@contactContent')->name('contact.edit');
            Route::post('/contact', 'ContentController@updateContact')->name('contact.update');

            Route::get('/body/1', 'ContentController@bodyContent')->name('mission.edit');
            Route::get('/body/2', 'ContentController@bodyContent')->name('vision.edit');
            Route::get('/body/3', 'ContentController@bodyContent')->name('value.edit');

            Route::post('/body', 'ContentController@updateBodyContent')->name('body.update');

            Route::get('/wkhours', 'ContentController@workingHours')->name('wkhours.edit');
            Route::post('/wkhours', 'ContentController@updateWorkingHours')->name('wkhours.update');

            // Testmonials management
            Route::resource('testmonial','TestmonialController')->except('show')->names([
                'index' => 'testmonial.index',
                'create' => 'testmonial.create',
                'store' => 'testmonial.store',
                'edit' => 'testmonial.edit',
                'update' => 'testmonial.update',
                'destroy' => 'testmonial.destroy'
            ]);
        });

        // membership
        Route::group(['prefix' => 'pendings', 'as' => 'pendings.'], function() {
            Route::get('/', 'PaymentOfflineController@index')->name('index');

            Route::get('/approve/{id}', 'PaymentOfflineController@approve')->name('approve');
            Route::delete('/decline/{id}', 'PaymentOfflineController@delete')->name('delete');
        });

app/Http/Controllers/Admin/AdminUserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Http\Requests\AdminUserRequest;

use App\Admin;
use App\Enums\UserType;

class AdminUserController extends Controller
{
    public function index()
    {
        $users = Admin::where('role_id', UserType::ADMIN)->get();
        return view("admin.admin_users.list", [
            "users" => $users
        ]);
    }

    public function create()
    {
        return view("admin.admin_users.add");
    }

    public function store(AdminUserRequest $request)
    {
        $data = $request->all();
        $data['password'] = bcrypt($data['password']);

        $user = Admin::Create($data);

        return redirect()->route("admin.adminusers.index");
    }

    public function edit($id)
    {
        $user = Admin::find($id);

        return view("admin.admin_users.edit", [
            'user' => $user
        ]);
    }

    public function update($id, AdminUserRequest $request)
    {
        $user = Admin::find($id);
        if ($user) {
            $user->email = $request->input('email');

            if ($request->input("password")){
                $user->password = bcrypt($request->input("password"));
            }
    
            $user->save();
        }
        
        return redirect()->route("admin.adminusers.index");
    }

    public function destroy($id)
    {
        $user = Admin::find($id);
        if ($user) {
            $user->delete();
        }
        
        return redirect()->route("admin.adminusers.index");
    }
}

resources/views/admin/admin_users/add.blade.php
@extends("admin.layouts.layout") 
@section("title","Admin Users") 
@section("subtitle","Add") 

@section("css")
@endsection
 
@section("breadcumps")
  <li><a href="{{route('admin.home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="{{route('admin.adminusers.index')}}">Admin Users</a></li>
  <li class="active">Add</li>
@endsection
 
@section("content")
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!-- Default box -->
    <a href="{{route('admin.adminusers.index')}}">
      <i class="fa fa-angle-double-left"></i> Back to all  <span class="text-lowercase">admin users</span>
    </a><br /><br />

    <form method="POST" action="{{route('admin.adminusers.store')}}" accept-charset="UTF-8">
      {{csrf_field()}}
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Add a new user</h3>
        </div>
        <!-- input field row -->
        <div class="box-body">

          <!-- email -->
          <div class="form-group">
            <label>Email</label>
            <span class="required">*</span>
            <input type="email" name="email" value="{{old('email')}}" placeholder="Email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" />
            @if ($errors->has("email"))
              <span class="invalid-feedback">{{ $errors->first("email") }}</span> 
            @endif
          </div>
          <!--./ email -->

          <div class="row">
            <!-- password -->
            <div class="form-group col-md-6">
              <label>Password</label>
              <span class="required">*</span>
              <input type="password" name="password" placeholder="Password"
                class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}" />
              @if ($errors->has("password"))
                <span class="invalid-feedback">{{ $errors->first("password") }}</span>
              @endif
            </div>
            <!--./ password -->
            <!-- password confirmation -->
            <div class="form-group col-md-6">
              <label>Password Confirm</label>
              <span class="required">*</span>
              <input type="password" name="password_confirmation" placeholder="Password Confirm"
                class="form-control" />
            </div>
            <!--./ password confirmation -->
          </div>
        </div>
        <!--./ input field row -->
        <div class="box-footer">
          <div class="form-group text-center saveActions">
            <input type="hidden" name="save_action" value="save_and_back" />
            <div class="btn-group">
              <button type="submit" class="btn btn-success">
                <span class="fa fa-save" role="presentation" aria-hidden="true"></span> &nbsp;
                <span data-value="save_and_back">Save and back</span>
              </button>
            </div>
            <a href="{{route('admin.adminusers.index')}}" class="btn btn-danger"><span class="fa fa-ban"></span> &nbsp;Cancel</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection
 
@section("js")
@endsection

resources/views/admin/admin_users/edit.blade.php
@php
  $email = old("email", $user->email);
@endphp

@extends("admin.layouts.layout")
@section("title","Admin Users") 
@section("subtitle","Edit") 
@section("css")
  
@endsection
 
@section("breadcumps")
  <li><a href="{{route('admin.home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="{{route('admin.adminusers.index')}}">Admin Users</a></li>
  <li class="active">Edit</li>
@endsection
 
@section("content")
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!-- Default box -->
    <a href="{{route('admin.adminusers.index')}}">
      <i class="fa fa-angle-double-left"></i> Back to all  <span class="text-lowercase">users</span>
    </a><br /><br />

    <form method="POST" action="{{route('admin.adminusers.update', ['id' => $user->id])}}" accept-charset="UTF-8">
      @csrf
      <input name="_method" type="hidden" value="PUT">
      <input name="id" type="hidden" value="{{$user->id}}">

      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit user</h3>
        </div>
        <!-- input field row -->
        <div class="box-body">

          <!-- email -->
          <div class="form-group">
            <label>Email</label>
            <span class="required">*</span>
            <input type="email" name="email" value="{{ $email }}" placeholder="Email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" />
            @if ($errors->has("email"))
              <span class="invalid-feedback">{{ $errors->first("email") }}</span> 
            @endif
          </div>
          <!--./ email -->

          <div class="row">
            
            <!-- password -->
            <div class="form-group col-md-6">
              <label>Password</label>
              <span class="required">*</span>
              <input type="password" name="password" placeholder="Password"
                class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}" />
              @if ($errors->has("password"))
                <span class="invalid-feedback">{{ $errors->first("password") }}</span>
              @endif
            </div>
            <!--./ password -->

            <!-- password confirmation -->
            <div class="form-group col-md-6">
              <label>Password Confirm</label>
              <span class="required">*</span>
              <input type="password" name="password_confirmation" placeholder="Password Confirm"
                class="form-control" />
            </div>
            <!--./ password confirmation -->

          </div>
        </div>
        <!--./ input field row -->

        <div class="box-footer">
          <div class="form-group text-center saveActions">
            <input type="hidden" name="save_action" value="save_and_back" />
            <div class="btn-group">
              <button type="submit" class="btn btn-success">
                <span class="fa fa-save" role="presentation" aria-hidden="true"></span> &nbsp;
                <span data-value="save_and_back">Save and back</span>
              </button>
            </div>
            <a href="{{route('admin.users')}}" class="btn btn-danger"><span class="fa fa-ban"></span> &nbsp;Cancel</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection
 
@section("js")
<script>
  $(function(){
    // http://jsfiddle.net/o31w8k6v/
    $("input[name=birthday]").datepicker({
        autoclose: true,
        format: "yyyy-mm-dd"
    })
  });

</script>
@endsection

resources/views/admin/admin_users/list.blade.php
@extends("admin.layouts.layout")
@section("title","Admin Users")
@section("subtitle","List")
@section("css")
  <link rel="stylesheet" href="{{ asset('public/adminTemplate/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection
 
@section("breadcumps")
  <li><a href="{{route('admin.home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Admin Users</li>
@endsection
 
@section("content")
<div class="box box-primary">
  <div class="box-header with-border">
    <a href="{{route('admin.adminusers.create')}}" class="btn btn-primary ladda-button" data-style="zoom-in">
      <span class="ladda-label">
        <i class="fa fa-plus"></i> Add user
      </span>
    </a>
  </div>
  <div class="box-body">
    <table id="usersTable" class="table table-bordered table-striped display dt-responsive nowrap dataTable dtr-inline">
      <thead>
        <tr>
          <th>Number</th>
          <th>Email</th>
          <th>Created</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        @foreach($users as $index => $user)
        <tr>
          <td>{{ $index + 1 }}</td>
          <td>{{ $user->email }}</td>
          <td>{{ $user->created_at }}</td>
          <td>
            <form action="{{route('admin.adminusers.destroy', ['id' => $user->id])}}" method="post" class="deleteForm">
              {{csrf_field()}}
              <input name="_method" type="hidden" value="DELETE">
              <a href="{{route('admin.adminusers.edit',["id " => $user->id])}}" class="btn btn-xs btn-primary">
                <i class="fa fa-edit"></i> Edit
              </a>
              <button type="button" class="btn btn-xs btn-danger" data-button-type="delete" onclick="onDel(event)">
                <i class="fa fa-trash"></i>Delete
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@endsection
 
@section("js")
<script src="{{ asset('public/adminTemplate/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('public/adminTemplate/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script>
  $("#usersTable").DataTable();

  function onDel(event) {
    event.preventDefault();
    $obj = $(event.target);
    if (confirm('Are you sure delete this membership?')) {
      $obj.closest('form').submit();
    }
  }
</script>
@endsection