routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'User\HomeController@index')->name('home');
Route::get('/payment/terms', 'User\PaymentController@terms')->name('payment.terms');

// -------- User Routes ----------
Route::group(['namespace' => 'User', 'as' => 'user.'], function () {

    Route::get('/priceterms/{type}', 'HomeController@priceTerms')->name('priceterms');
    // Authentication
    Route::group(['as' => 'auth.'], function() {
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('showLogin');
        Route::post('/login', 'Auth\LoginController@login')->name('login');
        Route::get('/signup', 'Auth\RegisterController@showRegistrationForm')->name('showSignup');
        Route::post('/signup', 'Auth\RegisterController@register')->name('signup');

        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

        Route::get('/forgot-password', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('forgot-password.showLinkRequestForm');
        Route::post('/forgot-password', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('forgot-password.sendResetLinkEmail');
        Route::get('/forgot-password/{token}', 'Auth\ResetPasswordController@showResetForm')->name('forgot-password.showResetForm');
        Route::post('/forgot-password-process', 'Auth\ResetPasswordController@reset')->name('forgot-password.reset');
    });

    // contact us
    Route::get('/contactus', 'ContactController@index')->name('contactus');

    Route::group(['middleware' => 'auth'], function() {
        // profile
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function(){
            Route::get('/', 'ProfileController@index')->name('index');
            Route::group(['middleware' => 'auth.primary'], function(){
                Route::get('/edit', 'ProfileController@edit')->name('edit');
                Route::put('/update', 'ProfileController@update')->name('update');
            });
            
        });
        
        // membership
        Route::group(['prefix' => 'membership', 'as' => 'membership.', 'middleware' => 'auth.primary'], function() {
            Route::get('/', 'MembershipController@index')->name('index');
            Route::get('/terms/{planTypeId}', 'MembershipController@terms')->name('terms');
            Route::get('/signup/{planTypeId}', 'MembershipController@signUp')->name('signup');

            Route::get('/create', 'MembershipController@create')->name('create');
            Route::post('/store', 'MembershipController@store')->name('store');
            Route::get('/edit/{pendingId}', 'MembershipController@edit')->name('edit');
            Route::put('/update', 'MembershipController@update')->name('update');
            Route::delete('/destroy/{pendingId}', 'MembershipController@delete')->name('destroy');

            Route::get('/plans', 'MembershipController@planSummary')->name('plans');
        });

        // payments
        Route::group(['prefix' => 'payments', 'as' => 'payments.', 'middleware' => 'auth.primary'], function(){
            Route::get('/', 'PaymentController@index')->name('index');
            Route::get('/paypal', 'PaymentController@paypal')->name('paypal');
            Route::get('/paypalSuccess', 'PaymentController@paypalSuccess')->name('paypalSuccess');
            Route::get('/cache', 'PaymentController@cache')->name('cache');
            Route::post('/stripe', 'PaymentController@stripe')->name('stripe');
            Route::get('/history', 'PaymentController@history')->name('history');
        });

        // members
        Route::group(['prefix' => 'members', 'as' => 'members.'], function(){
            Route::get('/', 'MemberController@index')->name('index');
            Route::group(['middleware' => 'auth.primary'], function(){
                Route::get('/planlist/{id}/{update_type}', 'MemberController@showUpgrade')->name('showupgrade');
                Route::post('/upgrade', 'MemberController@upgrade')->name('upgrade');
                Route::get('/upgrade/showterms', 'MemberController@showTerms')->name('upgrade.showterms');
                Route::get('/upgrade/showpayment', 'MemberController@showPayment')->name('upgrade.showpayment');
                Route::post('/upgrade/payment/stripe', 'MemberController@stripe')->name('upgrade.stripe');
                Route::post('/upgrade/payment/paypal', 'MemberController@paypal')->name('upgrade.paypal');
                Route::get('/upgrade/payment/paypalSuccess', 'MemberController@paypalSuccess')->name('upgrade.paypalsuccess');
                Route::post('/upgrade/payment/cache', 'MemberController@cache')->name('upgrade.cache');
            });
        });

        // pendings
        Route::group(['prefix' => 'pendings', 'as' => 'pendings.', 'middleware' => 'auth.primary'], function() {
            Route::get('/', 'MembershipController@pendings')->name('index');

            Route::get('/edit/{id}', 'MembershipController@pendings_edit')->name('edit');
            Route::put('/update', 'MembershipController@pendings_update')->name('update');
            Route::delete('/destroy/{id}', 'MembershipController@pendings_delete')->name('destroy');
        });
    });

    Route::get('/test', 'MemberController@test')->name('test');
    
});


// -------- Admin Routes ----------
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Authentication
    Route::group(['as' => 'auth.'], function() {
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('showLogin');
        Route::post('/login', 'Auth\LoginController@login')->name('login');
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
    
    Route::group(['middleware' => 'auth:admins'], function () {
        Route::get('/', 'AdminController@home')->name('home');

        // Admin Users management
        Route::resource('adminusers','AdminUserController')->except('show')->names([
            'index' => 'adminusers.index',
            'create' => 'adminusers.create',
            'store' => 'adminusers.store',
            'edit' => 'adminusers.edit',
            'update' => 'adminusers.update',
            'destroy' => 'adminusers.destroy'
        ]);

        // Users management
        Route::resource('users','UserController')->except('show')->names([
            'index' => 'users',
            'create' => 'users.create',
            'edit' => 'users.edit',
            'store' => 'users.store',
            'update' => 'users.update',
            'destroy' => 'users.destroy'
        ]);

        // Pending members management
        Route::group(['prefix' => 'users/pendingmembers', 'as' => 'pendingmembers'], function(){
            Route::get('/', 'PendingMemberController@index')->name('');
            Route::get('/create', 'PendingMemberController@create')->name('.create');
            Route::post('/store', 'PendingMemberController@store')->name('.store');
            Route::get('/edit/{id}', 'PendingMemberController@edit')->name('.edit');
            Route::put('/update/{id}', 'PendingMemberController@update')->name('.update');
            Route::put('/update/{id}', 'PendingMemberController@update')->name('.update');
            Route::delete('/{id}', 'PendingMemberController@destroy')->name('.destroy');
        });

        // print card management
        Route::group(['prefix' => 'users/print', 'as' => 'users.print.'], function(){
            Route::post('/upload', 'PrintController@uploadPhoto')->name('uploadphoto');
            Route::get('/showprint/{id}',  'PrintController@showPrint')->name('showprint');
            Route::get('/{id}', 'PrintController@edit')->name('edit');
        });

        // Payment management
        Route::group(['prefix' => 'payment', 'as' => 'payment.'], function(){
            Route::get('/pendinglist/{id}', 'PaymentController@pendingList')->name('pendinglist');
            Route::post('/pendingcheckout', 'PaymentController@pendingCheckout')->name('pendingcheckout');
            Route::get('/upgradeinfo', 'PaymentController@upgradeInfo')->name('upgradeinfo');
            Route::get('/checkout', 'PaymentController@checkout')->name('checkout');
            Route::get('/cache', 'PaymentController@cache')->name('cache');
            Route::post('/stripe', 'PaymentController@stripe')->name('stripe');
            Route::get('/paypal', 'PaymentController@paypal')->name('paypal');
            Route::get('/paypalSuccess', 'PaymentController@paypalSuccess')->name('paypalSuccess');
        });

        // Membership track
        Route::group(['prefix' => 'membertrack', 'as' => 'membertrack.'], function(){
            Route::get('/admin', 'MemberTrackController@byAdmin')->name('admin');
            Route::get('/user', 'MemberTrackController@byUser')->name('user');
        });
        

        // Slides management
        Route::resource('slides','SlideController')->except('show')->names([
            'index' => 'slides',
            'create' => 'slides.create',
            'store' => 'slides.store',
            'edit' => 'slides.edit',
            'update' => 'slides.update',
            'destroy' => 'slides.destroy'
        ]);

        // Membership Plans management
        Route::resource('memberplantypes','MemberPlanTypeController')->except('show')->names([
            'index' => 'memberplantypes',
            'edit' => 'memberplantypes.edit',
            'update' => 'memberplantypes.update'
        ]);

        // Discounts management
        Route::resource('discounts','DiscountController')->except('show')->names([

app/Http/Controllers/User/ContactController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContactController extends Controller
{
    public function index() {
        return view('user.contactus');
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Slide;
use App\Models\MemberPlanType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\HomeContent;
use App\Models\Testmonial;

class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest');
    }

    public function index() {
        $slides = Slide::orderBy('order')->get();
        $memberPlanTypes = MemberPlanType::all();
        $bodyContents = HomeContent::all();
        $testmonials = Testmonial::all();

        foreach ($bodyContents as $item) {
            $item->content = nl2br($item->content);
        }

        foreach ($testmonials as $item) {
            $item->content = nl2br($item->content);
        }

        return view('user.home', compact(
            'slides',
            'memberPlanTypes',
            'bodyContents',
            'testmonials'
        ));
    }

    public function priceTerms($type) {
        $plan = MemberPlanType::find($type);
        
        return view('user.priceterms', compact('plan'));
    }
}

app/Http/Controllers/User/MembershipController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

use App\Common\Utils;
use App\Enums\PlanType;
use App\Enums\MembershipStatus;
use App\Http\Requests\MemberRequest;

use App\User;
use App\Models\MembershipPending;
use App\Models\Country;
use App\Models\UserInfo;
use App\Models\Membership;
use App\Models\MemberPlanType;


class MembershipController extends Controller
{
    public function index() {
        $planTypes = MemberPlanType::all();

        $membership = Membership::where('user_id', auth()->id())
            ->where('status', MembershipStatus::PURCHASE)
            ->first();

        return view('user.membership.index', compact(
            'membership',
            'planTypes'
        ));
    }

    public function terms($planTypeId) {
        $plan = MemberPlanType::find($planTypeId);
        return view('user.membership.terms', compact(
            'planTypeId',
            'plan'
        ));
    }

    public function signUp($planTypeId, Request $request) {
        
        $membership = MembershipPending::updateOrCreate([
            'user_id' => auth()->id()
        ],[
            'owner_id' => auth()->id(),
            'status' => MembershipStatus::DRAFT,
            'plan_type_id' => $planTypeId,
        ]);

        return redirect()->route('user.membership.plans');
    }

    public function planSummary() {
        $members = MembershipPending::getMemberPlans(MembershipStatus::DRAFT, auth()->id());
        
        return view('user.membership.plans', compact(
            'members'
        ));
    }

    public function create() {
        $memberPlanTypes = MemberPlanType::all();
        $countries = Country::all();

        return view('user.membership.add', compact(
            'memberPlanTypes',
            'countries'
        ));
    }

    public function store(MemberRequest $request) {

        $isAdult = false;
        if (Utils::checkAdult($request->input('birthday'))) {
            $isAdult = true;
        }

        $data = [
            'primary_id' => auth()->id(),
            'email' => $request->input('email'),
            'password' => bcrypt($request->input('password')),
            'is_adult' => $isAdult,
            'relationship' => $request->input('relationship')
        ];

        $user = User::create($data);

        $data = $request->all();

        if (!$isAdult) {
            unset($data['phone']);
            unset($data['email']);
            unset($data['password']);
        }
        
        $data['user_id'] = $user->id;
        $userInfo = UserInfo::create($data);

        MembershipPending::updateOrCreate(
            [
                'user_id' => $user->id
            ],
            [
                'owner_id' => auth()->id(),
                'plan_type_id' => $request->input('plan_type'),
                'status' => MembershipStatus::DRAFT
            ]
        );

        if ($request->input('submit_type') == 'add') {
            return redirect()->route('user.membership.create');
        } else {
            return redirect()->route('user.membership.plans');
        }
        
    }

    public function edit($pendingId) {
        $member = MembershipPending::find($pendingId);
        if ($member) {
            $memberPlanTypes = MemberPlanType::all();
            $countries = Country::all();
    
            return view('user.membership.edit', compact(
                'member',
                'memberPlanTypes',
                'countries'
            ));
        } else {
            return redirect()->back();
        }
    }

    public function update(MemberRequest $request) {

        $isAdult = false;
        if (Utils::checkAdult($request->input('birthday'))) {
            $isAdult = true;
        }

        $data = [
            'email' => $request->input('email'),
            'is_adult' => $isAdult,
            'relationship' => $request->input('relationship')
        ];

        if ($request->input('password')) {
            $data['password'] = bcrypt($request->input('password'));
        }

        $member = User::find($request->input('user_id'));
        $member->update($data);

        $data = $request->all();
        
        $userInfo = $member->userInfo;
        $userInfo->update($data);

        $pendingId = $request->input('pending_id');
        $memberPending = MembershipPending::find($pendingId);
        $memberPending->plan_type_id = $data['plan_type'];
        $memberPending->save();

        return redirect()->route('user.membership.plans');
    }

    public function delete($pendingId) {
        $pendingItem = MembershipPending::find($pendingId);

        if ($pendingItem) {
            $user = $pendingItem->user;
            if ($user->id == auth()->id()) {
                $pendingItem->delete();
            } else {
                $user->delete();
            }
        }

        return redirect()->route('user.membership.plans');
    }

    public function pendings() {
        $members = MembershipPending::getMemberPlans(MembershipStatus::PENDING, auth()->id());
        
        return view('user.pendings.index', compact(
            'members'
        ));
    }

    public function pendings_edit($id) {
        $member = Member::getMember($id, MembershipStatus::PENDING, auth()->id());
        $countries = Country::all();

        return view('user.pendings.edit', compact(
            'member',
            'countries'
        ));
    }

    public function pendings_delete($id) {
        if ($id == auth()->id()) {
            $membershipId = auth()->user()->userInfo->membership_id;
            $membership = Membership::find($membershipId);
            if ($membership) {
                $membership->delete();
            }
        } else {
            $member = Member::find($id);
            if( $member) {
                $member->delete();
            }
        }

        return redirect()->route('user.pendings.index');
    }
}

resources/views/user/members/payment.blade.php
@php
    $stripeMonth = old('stripe_month', now()->month);
@endphp
@extends("user.layouts.page_layout")

@section('title', 'Payment')

@section("css")
@endsection

@section("page_content")

    <div class="row">
        <div class="col-md-12">
            @if (session('payment_error'))
                <div class="alert alert-danger">
                    {{ session('payment_error') }}
                </div>
            @endif
        </div>
        <div class="col-md-6">
            <form method="POST" action="{{ route('user.members.upgrade.stripe') }}" class="appointment-form ftco-animate">
                @csrf
                
                <div class="form-group">
                    <input type="text" class="form-control{{ $errors->has('stripe_number') ? ' is-invalid' : '' }}"
                        name="stripe_number" value="{{ old('stripe_number') }}" placeholder="Credit Card Number" required />
                    @if ($errors->has('stripe_number'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('stripe_number') }}</strong>
                        </span>
                    @endif
                </div>
    
                <div class="row">
                    <div class="form-group col-md-4">
                        <select name="stripe_month" class="form-control" required>
                            @for($i=1; $i<=12; $i++)
                                <option value="{{ $i }}"{{ $stripeMonth==$i ? ' selected' : ''}}>{{ $i }}</option>
                            @endfor
                        </select>
                        @if ($errors->has('stripe_month'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('stripe_month') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group col-md-4">
                        <select name="stripe_year" class="form-control" required>
                            @for($i=2019; $i<=2100; $i++)
                                <option value="{{ $i }}"{{ old('stripe_year')==$i ? ' selected' : ''}}>{{ $i }}</option>
                            @endfor
                        </select>
                        @if ($errors->has('stripe_year'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('stripe_year') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group col-md-4" >
                        <input type="text" class="form-control{{ $errors->has('stripe_cvc') ? ' is-invalid' : '' }}"
                            name="stripe_cvc" value="{{ old('stripe_cvc') }}" placeholder="CVC" required />
                        @if ($errors->has('stripe_cvc'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('stripe_cvc') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
    
                <div class="form-group">
                    <input type="text" class="form-control{{ $errors->has('stripe_name') ? ' is-invalid' : '' }}"
                        name="stripe_name" value="{{ old('stripe_name') }}" placeholder="Name on Card" required />
                    @if ($errors->has('stripe_name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('stripe_name') }}</strong>
                        </span>
                    @endif
                </div>
                
                <br />
                <div class="d-md-flex">
                    <div class="custom-control custom-checkbox" style="">
                        <input type="checkbox" class="custom-control-input" id="terms-check" required>
                        <label class="custom-control-label" for="terms-check">I Accept the Terms & Conditions of Wastina.com</label>
                    </div>
                </div>
                <br />
                <div class="d-md-flex">
                    <input type="submit" value="Checkout" class="btn btn-secondary" style="width:170px;height:50px;margin-left:5px;margin-top:10px;">
                    <a href="{{ route('user.membership.plans') }}">
                        <input type="button" value="Cancel" class="btn btn-danger" style="width:170px;height:50px;margin-left:20px;margin-top:10px;">
                    </a>
                </div>
            </form>
        </div>
        
        <div class="col-md-6">
            <div class="d-md-flex ml-md-4">
                <form method="POST" action="{{ route('user.members.upgrade.paypal') }}" id="form-paypal">
                    @csrf

                    <a href="#" onclick="confirmTerm(event)">
                        <img alt="Checkout with PayPal" style="width:190px;height:120px;" src="{{ asset('public/template/images/paypal.png') }}" />
                    </a>
                </form>
            </div>
            <form method="POST" action="{{ route('user.members.upgrade.cache') }}">
                @csrf

                <button type="submit" class="btn btn-secondary" style="width:200px;height:50px;margin-left:20px;margin-top:10px;">
                    Offline Checkout
                </button>
            </form>
        </div>
        
    </div>
@endsection

@section("js")
<script>
    $(function(){
        $('form').on('submit', function(e){
            e.preventDefault();
            if ($('#terms-check').is(':checked')) {
                this.submit();
            } else {
                alert('Please check Terms and Conditions');
            }            
        });
    });

    function confirmTerm(e) {
        e.preventDefault();
        if ($('#terms-check').is(':checked')) {
            $('#form-paypal').submit();
        } else {
            alert('Please check Terms and Conditions');
        }     
    }
</script>
@endsection

resources/views/user/members/showterms.blade.php
@php
    
@endphp
@extends("user.layouts.page_layout")

@section('title', 'Upgrade Summary')

@section("css")
    <style>
        .container {
            max-width: 1500px;
        }
    </style>
@endsection

@section("page_content")
    <div class="row d-flex align-items-stretch no-gutters">
        <div class="col-md-12 p-4 p-md-5 p-md-0 order-md-last bg-light">
            <h3 class="text-center">
                Upgrade "{{ $membership->user->relationship }}"'s plan from "{{ $membership->planType->name }}" to "{{ $targetPlan->name}}"
            </h3>
            <br />
            <h4>
                Membership will be expired by "{{ $membership->expires_in }}"
            </h4>

            <h4>
                "{{ $membership->planType->name }}" Monthly Price: 
                @if ($membership->user->is_adult)
                    ${{ $membership->planType->adult_price }}
                @else
                    ${{ $membership->planType->child_price }}
                @endif
            </h4>

            <h4>
                "{{ $targetPlan->name }}" Monthly Price: 
                @if ($membership->user->is_adult)
                    ${{ $targetPlan->adult_price }}
                @else
                    ${{ $targetPlan->child_price }}
                @endif
            </h4>

            <h4>
                Rest Month: {{ $restMonth }}
            </h4>

            <h4>
                Amount to pay: ${{ $amount }}
            </h4>
            

            <div class="text-center">
                <a href="{{ route('user.members.upgrade.showpayment') }}"><button type="button" class="btn btn-secondary mr-5">Checkout</button></a>
                <a href="{{ route('user.members.index') }}"><button type="button" class="btn btn-secondary">Return to list</button></a>
            </div>
        </div>
    </div>
@endsection

@section("js")
<script>
</script>
@endsection

resources/views/user/members/upgrade.blade.php
@php
    $planTypeId = $membership->plan_type_id;
    if($membership->status == 4) {
        $planTypeId = 0;
    }
@endphp
@extends("user.layouts.page_layout")

@section('title', 'Upgrade Membership')

@section("css")
    <style>
        .container {
            max-width: 1500px;
        }
    </style>
@endsection

@section("page_content")
    <div class="row d-flex align-items-stretch no-gutters">
        <div class="col-md-12 p-4 p-md-5 p-md-0 order-md-last bg-light">
            <h3 class="text-center">
                @if($membership->status == 3)
                    This member({{ $membership->user->relationship }}) purchased "{{$membership->planType->name}}" plan.
                @elseif($membership->status == 4)
                    This member({{ $membership->user->relationship }}) has been expired.
                @endif
            </h3>
            <br />
            
            <div class="row">
                @foreach($planTypes as $plan)
                    <!-- Plan Item -->
                    <div class="col-12 col-md-4">
                        <div class="rs-pricing-1 bg-primary-1 text-white mb-5{{ $plan->id == $planTypeId ? ' active' : '' }}"
                            data-value="{{ $plan->id }}">
                            <h3 class="title">{{ $plan->name }}</h3>
                            <div class="price">
                                <div>
                                    <span class="unit">$</span>{{ $membership->user->is_adult == 1 ? $plan->adult_price : $plan->child_price }}
                                    <span class="unit mt-3"> /mo </span>
                                </div>
                            </div>
                            <div class="features">
                                <ul>
                                    <li>{{ $plan->desc_first }}</li>
                                    <li>{{ $plan->desc_second }}</li>
                                    <li>{{ $plan->desc_third }}</li>
                                </ul>
                            </div>
                            <div class="action">
                                <form method="POST" action="{{ route('user.members.upgrade') }}">
                                    @csrf
                                    
                                    <input type="hidden" name="membership_id" value="{{ $membership->id }}" />
                                    <input type="hidden" name="plan_type" value="{{ $plan->id }}" />
                                    <input type="hidden" name="update_type" value="{{ $updateType }}" />

                                    <button type="submit" class="btn btn-secondary{{$plan->id <= $planTypeId ? ' isDisabled' : ''}}">
                                        Select
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!--./ Plan Item -->
                @endforeach
            </div>

            <div class="text-center">
                <a href="{{ route('user.members.index') }}"><button type="button" class="btn btn-secondary">Return to list</button></a>
            </div>
        </div>
    </div>
@endsection

@section("js")
<script>
    $(function(){
        $('.rs-pricing-1').on('click', function(){
            var $submitForm = $(this).find('form');
            var $submitButton = $(this).find('form button[type=submit]');
            if (!($submitButton.hasClass('isDisabled'))) {
                $submitForm.submit();
            }
        });
    });
</script>
@endsection