routes/web.php
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function(){
            Route::get('/', 'ProfileController@index')->name('index');
            Route::group(['middleware' => 'auth.primary'], function(){
                Route::get('/edit', 'ProfileController@edit')->name('edit');
                Route::put('/update', 'ProfileController@update')->name('update');
            });
            
        });
        
        // membership
        Route::group(['prefix' => 'membership', 'as' => 'membership.', 'middleware' => 'auth.primary'], function() {
            Route::get('/', 'MembershipController@index')->name('index');
            Route::get('/terms/{planTypeId}', 'MembershipController@terms')->name('terms');
            Route::get('/signup/{planTypeId}', 'MembershipController@signUp')->name('signup');

            Route::get('/create', 'MembershipController@create')->name('create');
            Route::post('/store', 'MembershipController@store')->name('store');
            Route::get('/edit/{pendingId}', 'MembershipController@edit')->name('edit');
            Route::put('/update', 'MembershipController@update')->name('update');
            Route::delete('/destroy/{pendingId}', 'MembershipController@delete')->name('destroy');

            Route::get('/plans', 'MembershipController@planSummary')->name('plans');
        });

        // payments
        Route::group(['prefix' => 'payments', 'as' => 'payments.', 'middleware' => 'auth.primary'], function(){
            Route::get('/', 'PaymentController@index')->name('index');
            Route::get('/paypal', 'PaymentController@paypal')->name('paypal');
            Route::get('/paypalSuccess', 'PaymentController@paypalSuccess')->name('paypalSuccess');
            Route::get('/cache', 'PaymentController@cache')->name('cache');
            Route::post('/stripe', 'PaymentController@stripe')->name('stripe');
            Route::get('/history', 'PaymentController@history')->name('history');
        });

        // members
        Route::group(['prefix' => 'members', 'as' => 'members.'], function(){
            Route::get('/', 'MemberController@index')->name('index');
            Route::group(['middleware' => 'auth.primary'], function(){
                Route::get('/planlist/{id}/{update_type}', 'MemberController@showUpgrade')->name('showupgrade');
                Route::post('/upgrade', 'MemberController@upgrade')->name('upgrade');
                Route::get('/upgrade/showterms', 'MemberController@showTerms')->name('upgrade.showterms');
                Route::get('/upgrade/showpayment', 'MemberController@showPayment')->name('upgrade.showpayment');
                Route::post('/upgrade/payment/stripe', 'MemberController@stripe')->name('upgrade.stripe');
                Route::post('/upgrade/payment/paypal', 'MemberController@paypal')->name('upgrade.paypal');
                Route::get('/upgrade/payment/paypalSuccess', 'MemberController@paypalSuccess')->name('upgrade.paypalsuccess');
                Route::post('/upgrade/payment/cache', 'MemberController@cache')->name('upgrade.cache');
            });
        });

        // pendings
        Route::group(['prefix' => 'pendings', 'as' => 'pendings.', 'middleware' => 'auth.primary'], function() {
            Route::get('/', 'MembershipController@pendings')->name('index');

            Route::get('/edit/{id}', 'MembershipController@pendings_edit')->name('edit');
            Route::put('/update', 'MembershipController@pendings_update')->name('update');
            Route::delete('/destroy/{id}', 'MembershipController@pendings_delete')->name('destroy');
        });
    });

    Route::get('/test', 'MemberController@test')->name('test');
    
});


// -------- Admin Routes ----------
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Authentication
    Route::group(['as' => 'auth.'], function() {
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('showLogin');
        Route::post('/login', 'Auth\LoginController@login')->name('login');
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
    
    Route::group(['middleware' => 'auth:admins'], function () {
        Route::get('/', 'AdminController@home')->name('home');

        // Admin Users management
        Route::resource('adminusers','AdminUserController')->except('show')->names([
            'index' => 'adminusers.index',
            'create' => 'adminusers.create',
            'store' => 'adminusers.store',
            'edit' => 'adminusers.edit',
            'update' => 'adminusers.update',
            'destroy' => 'adminusers.destroy'
        ]);

        // Users management
        Route::resource('users','UserController')->except('show')->names([
            'index' => 'users',
            'create' => 'users.create',
            'edit' => 'users.edit',
            'store' => 'users.store',
            'update' => 'users.update',
            'destroy' => 'users.destroy'
        ]);

        // Pending members management
        Route::group(['prefix' => 'users/pendingmembers', 'as' => 'pendingmembers'], function(){
            Route::get('/', 'PendingMemberController@index')->name('');
            Route::get('/create', 'PendingMemberController@create')->name('.create');
            Route::post('/store', 'PendingMemberController@store')->name('.store');
            Route::get('/edit/{id}', 'PendingMemberController@edit')->name('.edit');
            Route::put('/update/{id}', 'PendingMemberController@update')->name('.update');
            Route::put('/update/{id}', 'PendingMemberController@update')->name('.update');
            Route::delete('/{id}', 'PendingMemberController@destroy')->name('.destroy');
        });

        // print card management
        Route::group(['prefix' => 'users/print', 'as' => 'users.print.'], function(){
            Route::post('/upload', 'PrintController@uploadPhoto')->name('uploadphoto');
            Route::get('/showprint/{id}',  'PrintController@showPrint')->name('showprint');
            Route::get('/{id}', 'PrintController@edit')->name('edit');
        });

        // Payment management
        Route::group(['prefix' => 'payment', 'as' => 'payment.'], function(){
            Route::get('/pendinglist/{id}', 'PaymentController@pendingList')->name('pendinglist');
            Route::post('/pendingcheckout', 'PaymentController@pendingCheckout')->name('pendingcheckout');
            Route::get('/upgradeinfo', 'PaymentController@upgradeInfo')->name('upgradeinfo');
            Route::get('/checkout', 'PaymentController@checkout')->name('checkout');
            Route::get('/cache', 'PaymentController@cache')->name('cache');
            Route::post('/stripe', 'PaymentController@stripe')->name('stripe');
            Route::get('/paypal', 'PaymentController@paypal')->name('paypal');
            Route::get('/paypalSuccess', 'PaymentController@paypalSuccess')->name('paypalSuccess');
        });

        // Membership track
        Route::group(['prefix' => 'membertrack', 'as' => 'membertrack.'], function(){
            Route::get('/admin', 'MemberTrackController@byAdmin')->name('admin');
            Route::get('/user', 'MemberTrackController@byUser')->name('user');
        });
        

        // Slides management
        Route::resource('slides','SlideController')->except('show')->names([
            'index' => 'slides',
            'create' => 'slides.create',
            'store' => 'slides.store',
            'edit' => 'slides.edit',
            'update' => 'slides.update',
            'destroy' => 'slides.destroy'
        ]);

        // Membership Plans management
        Route::resource('memberplantypes','MemberPlanTypeController')->except('show')->names([
            'index' => 'memberplantypes',
            'edit' => 'memberplantypes.edit',
            'update' => 'memberplantypes.update'
        ]);

        // Discounts management
        Route::resource('discounts','DiscountController')->except('show')->names([
            'index' => 'discounts.index',
            'create' => 'discounts.create',
            'store' => 'discounts.store',
            'edit' => 'discounts.edit',
            'update' => 'discounts.update',
            'destroy' => 'discounts.destroy'
        ]);

        // contents
        Route::group(['prefix' => 'contents', 'as' => 'contents.'], function() {
            Route::get('/contact', 'ContentController@contactContent')->name('contact.edit');
            Route::post('/contact', 'ContentController@updateContact')->name('contact.update');

            Route::get('/body/1', 'ContentController@bodyContent')->name('mission.edit');
            Route::get('/body/2', 'ContentController@bodyContent')->name('vision.edit');
            Route::get('/body/3', 'ContentController@bodyContent')->name('value.edit');

            Route::post('/body', 'ContentController@updateBodyContent')->name('body.update');

            Route::get('/wkhours', 'ContentController@workingHours')->name('wkhours.edit');
            Route::post('/wkhours', 'ContentController@updateWorkingHours')->name('wkhours.update');

            // Testmonials management
            Route::resource('testmonial','TestmonialController')->except('show')->names([
                'index' => 'testmonial.index',
                'create' => 'testmonial.create',
                'store' => 'testmonial.store',
                'edit' => 'testmonial.edit',
                'update' => 'testmonial.update',
                'destroy' => 'testmonial.destroy'
            ]);
        });

        // membership
        Route::group(['prefix' => 'pendings', 'as' => 'pendings.'], function() {
            Route::get('/', 'PaymentOfflineController@index')->name('index');

            Route::get('/approve/{id}', 'PaymentOfflineController@approve')->name('approve');
            Route::delete('/decline/{id}', 'PaymentOfflineController@delete')->name('delete');
        });

app/Http/Controllers/Admin/ContentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Enums\ContentType;
use App\Models\HomeContent;
use App\Models\ContactInfo;
use App\Models\WorkingHour;
use Illuminate\Support\Facades\DB;

class ContentController extends Controller
{
    public function bodyContent(Request $request)
    {
        $segments = $request->segments();
        $id = end($segments);

        $content = HomeContent::find($id);

        return view('admin.contents.body_edit', compact(
            'content'
        ));
    }

    public function updateBodyContent(Request $request) {

        $content = HomeContent::find($request->input('id'));
        $content->content = $request->input("content");

        $imageFile = $request->img_file;
        if ($imageFile) {
            $oldFileName = public_path('files/contents/' . $content->image);
            if (file_exists($oldFileName)) {
                \File::delete($oldFileName);
            }

            $fileName = time() . '.' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path('files/contents'), $fileName);
            $content->image = $fileName;
        }

        $content->save();
        return redirect()->back();
    }

    public function contactContent() {
        $content = ContactInfo::first();

        return view('admin.contents.contact_edit', compact(
            'content'
        ));
    }

    public function updateContact(Request $request) {
        $this->validate($request, [
            'email' => 'required|email',
            'phone' => 'required',
            'address' => 'required',
            'facebook' => 'required',
            'twitter' => 'required',
            'instagram' => 'required',
            'pinterest' => 'required',
        ]);

        ContactInfo::first()->update($request->all());

        return redirect()->back();
    }

    public function workingHours() {
        $workingHours = DB::table('working_hours')->get();

        return view('admin.contents.working_edit', compact(
            'workingHours'
        ));
    }

    public function updateWorkingHours(Request $request) {
        $hourList = [];

        // dd($request->input('open_status'));
        for ($i=0; $i<7; $i++) {
            
            $status = 0;
            if (array_search(($i), $request->input('open_status')) !== false) {
                $status = 1;
            }
            
            WorkingHour::find($i+1)->update([
                'start' => $request->input('start')[$i],
                'end' => $request->input('end')[$i],
                'open_status' => $status,
            ]);
        }

        return redirect()->back();
    }
}

resources/views/admin/contents/body_edit.blade.php
@extends("admin.layouts.layout")
@php
  $contentText = old("content", $content->content);
  $image = old("image", $content->image);
  $src = $content->image ? asset('public/files/contents/' . $content->image) : 'data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=';
@endphp
@section("title", $content->title) 
@section("subtitle","Edit") 
 
@section("breadcumps")
  <li><a href="{{route('admin.home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="#">Contents</a></li>
  <li class="active">Edit</li>
@endsection

@section("content")
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <form method="POST" action="{{route('admin.contents.body.update')}}" enctype="multipart/form-data" accept-charset="UTF-8">

      @csrf
      <input name="id" type="hidden" value="{{$content->id}}" />

      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit</h3>
        </div>
        <div class="box-body form-horizontal">
          <!-- content -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Content *</label>
            <div class="col-sm-10">
              <textarea name="content" maxlength="1000" rows="5" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">{{ $contentText }}</textarea>
              @if ($errors->has("content"))
                <span class="invalid-feedback">{{ $errors->first("content") }}</span> 
              @endif
            </div>
          </div>
          <!--./ content -->
          
          <!-- Image -->
          <div class="form-group" style="margin-top: 10px;">
            <label class="col-sm-2 control-label">Image *</label>
            <div class="col-sm-4">
              <input type="file" id="img_file" name="img_file" value="{{old('img_file')}}" accept="image/*"
                class="form-control {{ $errors->has('img_file') ? 'is-invalid' : '' }}"/>
              @if ($errors->has("img_file"))
                <span class="invalid-feedback">{{ $errors->first("img_file") }}</span>
              @endif
            </div>
            <div class="col-sm-6">
              <img id="thumb-icon" src="{{ $src }}" accept=".png" alt="thumbnail"/>
            </div>
          </div>
          <!--./ Image -->
        </div>
        <div class="box-footer">
          <div id="saveActions" class="form-group text-center">
            <div class="btn-group">
              <button type="submit" class="btn btn-success">
                <span class="fa fa-save" role="presentation" aria-hidden="true"></span> &nbsp;
                <span data-value="save_and_back">Save</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection
 
@section("js")
<script>
  var fileTypes = ['jpg', 'jpeg', 'png'];

  function readURL(input) {
      if (input.files && input.files[0]) {
        var extension = input.files[0].name.split('.').pop().toLowerCase(),  //file extension from input file
            imgType = fileTypes.indexOf(extension) > -1;
        
        if (imgType) {
          var reader = new FileReader();

          reader.onload = function (e) {
              $('#thumb-icon').attr('src', e.target.result);
          }

          reader.readAsDataURL(input.files[0]);
        } else {
          alert('You can select only image file.');
          var imgInput = $('#img_file');
          imgInput.replaceWith(imgInput.val('').clone(true));
        }
      }
  }

  $("#img_file").change(function(){
    readURL(this);
  });
</script>
@endsection

resources/views/admin/contents/contact_edit.blade.php
@extends("admin.layouts.layout")
@php
  $email = old("email", $content->email);
  $phone = old("phone", $content->phone);
  $address = old("address", $content->address);
  $url = old("address", $content->url);
  $facebook = old("facebook", $content->facebook);
  $twitter = old("twitter", $content->twitter);
  $instagram = old("instagram", $content->instagram);
  $pinterest = old("pinterest", $content->pinterest);
@endphp
@section("title","Contact Informations") 
@section("subtitle","Edit") 
 
@section("breadcumps")
  <li><a href="{{route('admin.home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="#">Contact Informations</a></li>
  <li class="active">Edit</li>
@endsection

@section("content")
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!-- Default box -->
    <form method="POST" action="{{route('admin.contents.contact.update')}}">

      @csrf

      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit</h3>
        </div>
        <div class="box-body form-horizontal">

          <!-- email -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="email" value="{{ $email }}" placeholder="Email"
                class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" />
              @if ($errors->has("email"))
                <span class="invalid-feedback">{{ $errors->first("email") }}</span>
              @endif
            </div>
          </div>
          <!--./ email -->

          <!-- phone -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Phone</label>
            <div class="col-sm-10">
              <input type="text" name="phone" value="{{ $phone }}" placeholder="Phone"
                class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" />
              @if ($errors->has("phone"))
                <span class="invalid-feedback">{{ $errors->first("phone") }}</span>
              @endif
            </div>
          </div>
          <!--./ phone -->

          <!-- address -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Address</label>
            <div class="col-sm-10">
              <input type="text" name="address" value="{{ $address }}" placeholder="Address"
                class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}" />
              @if ($errors->has("address"))
                <span class="invalid-feedback">{{ $errors->first("address") }}</span>
              @endif
            </div>
          </div>
          <!--./ address -->

          <!-- url -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Url</label>
            <div class="col-sm-10">
              <input type="text" name="url" value="{{ $url }}" placeholder="Url"
                class="form-control {{ $errors->has('url') ? 'is-invalid' : '' }}" />
              @if ($errors->has("url"))
                <span class="invalid-feedback">{{ $errors->first("url") }}</span>
              @endif
            </div>
          </div>
          <!--./ url -->

          <!-- facebook -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Facebook</label>
            <div class="col-sm-10">
              <input type="text" name="facebook" value="{{ $facebook }}" placeholder="Facebook"
                class="form-control {{ $errors->has('facebook') ? 'is-invalid' : '' }}" />
              @if ($errors->has("facebook"))
                <span class="invalid-feedback">{{ $errors->first("facebook") }}</span>
              @endif
            </div>
          </div>
          <!--./ facebook -->

          <!-- twitter -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Twitter</label>
            <div class="col-sm-10">
              <input type="text" name="twitter" value="{{ $twitter }}" placeholder="Twitter"
                class="form-control {{ $errors->has('twitter') ? 'is-invalid' : '' }}" />
              @if ($errors->has("twitter"))
                <span class="invalid-feedback">{{ $errors->first("twitter") }}</span>
              @endif
            </div>
          </div>
          <!--./ twitter -->

          <!-- instagram -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Instagram</label>
            <div class="col-sm-10">
              <input type="text" name="instagram" value="{{ $instagram }}" placeholder="Instagram"
                class="form-control {{ $errors->has('instagram') ? 'is-invalid' : '' }}" />
              @if ($errors->has("instagram"))
                <span class="invalid-feedback">{{ $errors->first("instagram") }}</span>
              @endif
            </div>
          </div>
          <!--./ instagram -->

          <!-- pinterest -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Pinterest</label>
            <div class="col-sm-10">
              <input type="text" name="pinterest" value="{{ $pinterest }}" placeholder="Pinterest"
                class="form-control {{ $errors->has('pinterest') ? 'is-invalid' : '' }}" />
              @if ($errors->has("pinterest"))
                <span class="invalid-feedback">{{ $errors->first("pinterest") }}</span>
              @endif
            </div>
          </div>
          <!--./ pinterest -->

        </div>

        <div class="box-footer">
          <div id="saveActions" class="form-group text-center">
            <div class="btn-group">
              <button type="submit" class="btn btn-success">
                <span class="fa fa-save" role="presentation" aria-hidden="true"></span> &nbsp;
                <span data-value="save_and_back">Save</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection
 
@section("js")

@endsection

resources/views/admin/contents/working_edit.blade.php
@extends("admin.layouts.layout")
@php

@endphp
@section("title","Contact Informations") 
@section("subtitle","Edit") 
 
@section("breadcumps")
  <li><a href="{{route('admin.home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="#">Contact Informations</a></li>
  <li class="active">Edit</li>
@endsection

@section("content")
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!-- Default box -->
    <form method="POST" action="{{route('admin.contents.wkhours.update')}}">

      @csrf

      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit</h3>
        </div>
        <div class="box-body form-horizontal">

          <div class="form-group row">
            <div class="col-sm-3 text-center">Week Day</div>
            <div class="col-sm-3 text-center">Start Time</div>
            <div class="col-sm-3 text-center">End Time</div>
            <div class="col-sm-2 text-center">Open Status</div>
          </div>

          @foreach($workingHours as $index=>$item)
            <div class="form-group row">
              <label class="col-sm-3 text-center">{{ $item->week_day }}</label>
              <div class="col-sm-3 text-center">
                <input type="time" name="start[]" value="{{ $item->start }}" placeholder="start time" />
              </div>
              <div class="col-sm-3 text-center">
                <input type="time" name="end[]" value="{{ $item->end }}" placeholder="start time" />
              </div>
              <div class="col-sm-2 text-center">
                <input type="checkbox" name="open_status[]" value="{{$index}}" {{$item->open_status == 1 ? 'checked': ''}}/>
              </div>
            </div>
          @endforeach
          

        </div>

        <div class="box-footer">
          <div id="saveActions" class="form-group text-center">
            <div class="btn-group">
              <button type="submit" class="btn btn-success">
                <span class="fa fa-save" role="presentation" aria-hidden="true"></span> &nbsp;
                <span data-value="save_and_back">Save</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection
 
@section("js")

@endsection